/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#303031",
        "on-background": "#1b1c1c",
        "surface-bright": "#fbf9f9",
        "surface-dim": "#dbdad9",
        "tertiary-container": "#b5b3ae",
        "error": "#ba1a1a",
        "primary-container": "#d4af37",
        "on-surface-variant": "#4d4635",
        "on-secondary-fixed": "#1c1b1b",
        "secondary-fixed": "#e5e2e1",
        "secondary-container": "#e2dfde",
        "on-surface": "#1b1c1c",
        "on-primary-fixed": "#241a00",
        "surface-container-highest": "#e3e2e2",
        "on-tertiary-container": "#464541",
        "on-secondary-container": "#636262",
        "outline-variant": "#d0c5af",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e9e8e7",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f2f0f0",
        "secondary": "#5f5e5e",
        "primary-fixed": "#ffe088",
        "tertiary-fixed-dim": "#c9c6c1",
        "primary": "#735c00",
        "outline": "#7f7663",
        "on-tertiary-fixed": "#1c1c18",
        "surface": "#fbf9f9",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-low": "#f5f3f3",
        "on-primary-container": "#554300",
        "on-tertiary-fixed-variant": "#474743",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#474746",
        "on-error": "#ffffff",
        "surface-variant": "#e3e2e2",
        "primary-fixed-dim": "#e9c349",
        "background": "#fbf9f9",
        "inverse-primary": "#e9c349",
        "tertiary-fixed": "#e5e2dc",
        "surface-tint": "#735c00",
        "on-primary-fixed-variant": "#574500",
        "on-error-container": "#93000a",
        "tertiary": "#5f5e5a",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-container": "#efeded"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-margin": "20px",
        "stack-sm": "12px",
        "stack-lg": "40px",
        "base": "8px",
        "gutter": "16px",
        "stack-md": "24px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Playfair Display"],
        "headline-md": ["Playfair Display"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Playfair Display"],
        "body-md": ["Inter"],
        "display-lg": ["Playfair Display"],
        "title-lg": ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display-lg": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "title-lg": ["20px", {"lineHeight": "28px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
